name: Test Linuxkit Builder

on: push

jobs:
  build-linuxkit-zfs:
    strategy:
      matrix:
        os: [macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: System uname
        run: uname -a
      - name: Setup Docker
        run: ./scripts/setup-docker-osx.sh
      - name: docker uname
        run: docker run busybox uname -a
      - name: docker build
        run: docker build . -t linuxkit-builder
      - name: docker run
        run: docker run linuxkit-builder