name: Test Linuxkit Builder

on: push

jobs:
  build-linuxkit-zfs:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: System uname
        run: uname -a
        shell: bash
      - name: docker uname
        run: docker run busybox uname -a
        shell: bash